# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.srcs/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0.xci
# IP: The module: 'top_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/bd_d0e7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7 || ORIG_REF_NAME==bd_d0e7} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_0/bd_d0e7_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_1/bd_d0e7_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_const_0_0 || ORIG_REF_NAME==bd_d0e7_const_0_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_2/bd_d0e7_M00_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_d0e7_M00_AXI_nsu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_3/bd_d0e7_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_4/bd_d0e7_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_5/bd_d0e7_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_6/bd_d0e7_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_MC0_ddrc_0 || ORIG_REF_NAME==bd_d0e7_MC0_ddrc_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_6/ip_0/bd_d0e7_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_d0e7_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_d0e7_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S00_AXI_nmu_0} -quiet] {/bd_d0e7_S00_AXI_nmu_0_top_INST } ]/bd_d0e7_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_d0e7_M00_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_d0e7_M00_AXI_nsu_0} -quiet] {/bd_d0e7_M00_AXI_nsu_0_top_INST } ]/bd_d0e7_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_d0e7_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S01_AXI_nmu_0} -quiet] {/bd_d0e7_S01_AXI_nmu_0_top_INST } ]/bd_d0e7_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_d0e7_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S02_AXI_nmu_0} -quiet] {/bd_d0e7_S02_AXI_nmu_0_top_INST } ]/bd_d0e7_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_d0e7_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S03_AXI_nmu_0} -quiet] {/bd_d0e7_S03_AXI_nmu_0_top_INST } ]/bd_d0e7_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_6/hdl/par/bd_d0e7_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_MC0_ddrc_0 || ORIG_REF_NAME==bd_d0e7_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.srcs/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0.xci
# IP: The module: 'top_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/bd_d0e7.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7 || ORIG_REF_NAME==bd_d0e7} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_0/bd_d0e7_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_1/bd_d0e7_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_const_0_0 || ORIG_REF_NAME==bd_d0e7_const_0_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_2/bd_d0e7_M00_AXI_nsu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_d0e7_M00_AXI_nsu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_3/bd_d0e7_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_4/bd_d0e7_S02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_5/bd_d0e7_S03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_6/bd_d0e7_MC0_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_MC0_ddrc_0 || ORIG_REF_NAME==bd_d0e7_MC0_ddrc_0} -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_6/ip_0/bd_d0e7_MC0_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d0e7_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_d0e7_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_d0e7_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S00_AXI_nmu_0} -quiet] {/bd_d0e7_S00_AXI_nmu_0_top_INST } ]/bd_d0e7_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_d0e7_M00_AXI_nsu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_d0e7_M00_AXI_nsu_0} -quiet] {/bd_d0e7_M00_AXI_nsu_0_top_INST } ]/bd_d0e7_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_d0e7_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S01_AXI_nmu_0} -quiet] {/bd_d0e7_S01_AXI_nmu_0_top_INST } ]/bd_d0e7_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_d0e7_S02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S02_AXI_nmu_0} -quiet] {/bd_d0e7_S02_AXI_nmu_0_top_INST } ]/bd_d0e7_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_d0e7_S03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_d0e7_S03_AXI_nmu_0} -quiet] {/bd_d0e7_S03_AXI_nmu_0_top_INST } ]/bd_d0e7_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/bd_0/ip/ip_6/hdl/par/bd_d0e7_MC0_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d0e7_MC0_ddrc_0 || ORIG_REF_NAME==bd_d0e7_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_axi_noc_0_0/top_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
