# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.srcs/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1.xci
# IP: The module: 'top_fl_vadd_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add_s || ORIG_REF_NAME==fp_add_s} -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_fl_vadd_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.srcs/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1.xci
# IP: The module: 'top_fl_vadd_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add_s || ORIG_REF_NAME==fp_add_s} -quiet] -quiet

# XDC: /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_fl_vadd_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
