# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.runs/top_fl_vadd_top_0_1_synth_1/top_fl_vadd_top_0_1.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "top_fl_vadd_top_0_1_synth_1" START { ROLLUP_AUTO }
set_param netlist.writeMacroLevel 0
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-31435-omar-Dell-G15-5515/incrSyn
set_param chipscope.flow 0
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/mref
create_project -in_memory -part xcvc1902-vsva2197-2MP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.cache/wt [current_project]
set_property parent.project_path /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vck190:part0:3.3 [current_project]
update_ip_catalog
set_property ip_output_repo /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/interfaces/axi_lite_if.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/interfaces/axi_stream_if.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/axl_ps_adapters/axl_ps_adapter.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/basic_sync_fifo/basic_sync_fifo.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ctrl_data_fifo/ctrl_data_fifo.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/fl_vadd/fl_vadd.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/interfaces/ps_if.sv
  /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/s2mm/s2mm.sv
}
read_verilog -library xil_defaultlib /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/fl_vadd/fl_vadd_top.v
read_ip -quiet /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s.xci
set_property used_in_implementation false [get_files -all /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s_ooc.xdc]

read_ip -quiet /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.srcs/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1.xci
set_property used_in_implementation false [get_files -all /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_fl_vadd_top_0_1 -part xcvc1902-vsva2197-2MP-e-S -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all top_fl_vadd_top_0_1_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_fl_vadd_top_0_1.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_fl_vadd_top_0_1_utilization_synth.rpt -pb top_fl_vadd_top_0_1_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.runs/top_fl_vadd_top_0_1_synth_1/top_fl_vadd_top_0_1.dcp /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.ip_user_files/ip/top_fl_vadd_top_0_1]} {
  catch { 
    file copy -force /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_stub.v /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.ip_user_files/ip/top_fl_vadd_top_0_1
  }
}

if {[file isdir /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.ip_user_files/ip/top_fl_vadd_top_0_1]} {
  catch { 
    file copy -force /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.gen/sources_1/bd/top/ip/top_fl_vadd_top_0_1/top_fl_vadd_top_0_1_stub.vhdl /home/omar/Documents/year-4/FYP/mudkip/vivado/mudkip.ip_user_files/ip/top_fl_vadd_top_0_1
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "top_fl_vadd_top_0_1_synth_1" END { }
