# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s.xci
# IP: The module: 'fp_add_s' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_add_s'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s.xci
# IP: The module: 'fp_add_s' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/omar/Documents/year-4/FYP/mudkip/hw/rtl/ips/fp_add_s/fp_add_s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_add_s'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
