name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Checkout repository
      uses: LazyPanda07/get-gtest@v1.1

    # Verilator setup (already in your workflow)
    - name: Install Verilator from source
      run: |
        sudo apt-get update
        sudo apt-get install -y git perl python3 make autoconf g++ flex bison ccache verilator

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make libgmp-dev libmpfr-dev

    - name: Build all targets
      run: make -C hw default

    - name: Run Google Tests
      run: make -C hw test
